# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  scrape_battlefield_6_patches:
    class: ScrapeBattlefield6Job
    queue: default
    schedule: every monday at 5am

  scrape_baldurs_gate_3_patches:
    class: ScrapeBaldursGate3Job
    queue: default
    schedule: every monday at 5:15am

  scrape_genshin_impact_patches:
    class: ScrapeGenshinImpactJob
    queue: default
    schedule: every monday at 5:20am

  scrape_arc_raiders_patches:
    class: ScrapeArcRaidersJob
    queue: default
    schedule: every monday at 5:30am

  scrape_marvel_rivals_patches:
    class: ScrapeMarvelRivalsJob
    queue: default
    schedule: every monday at 6am

  scrape_warzone_patches:
    class: ScrapeWarzoneJob
    queue: default
    schedule: every monday at 7am

  scrape_fortnite_patches:
    class: ScrapeFortniteJob
    queue: default
    schedule: every monday at 8am

  scrape_apex_legends_patches:
    class: ScrapeApexLegendsJob
    queue: default
    schedule: every monday at 9am

  scrape_ea_sports_fc_26_patches:
    class: ScrapeEaSportsFc26Job
    queue: default
    schedule: every monday at 9:30am

  scrape_helldivers_2_patches:
    class: ScrapeHelldivers2Job
    queue: default
    schedule: every monday at 10am

  scrape_destiny_2_patches:
    class: ScrapeDestiny2Job
    queue: default
    schedule: every monday at 11am

  scrape_minecraft_patches:
    class: ScrapeMinecraftJob
    queue: default
    schedule: every monday at 12pm

  scrape_league_of_legends_patches:
    class: ScrapeLeagueOfLegendsJob
    queue: default
    schedule: every monday at 12:30pm

  scrape_counter_strike_2_patches:
    class: ScrapeCounterStrike2Job
    queue: default
    schedule: every monday at 12:45pm

  scrape_valorant_patches:
    class: ScrapeValorantJob
    queue: default
    schedule: every monday at 1pm

  scrape_overwatch_2_patches:
    class: ScrapeOverwatch2Job
    queue: default
    schedule: every monday at 1:30pm

  scrape_resident_evil_requiem_patches:
    class: ScrapeResidentEvilRequiemJob
    queue: default
    schedule: every monday at 1:45pm

  scrape_horizon_forbidden_west_patches:
    class: ScrapeHorizonForbiddenWestJob
    queue: default
    schedule: every monday at 1:50pm

  scrape_cyberpunk_2077_patches:
    class: ScrapeCyberpunk2077Job
    queue: default
    schedule: every monday at 1:55pm

  scrape_space_marine_2_patches:
    class: ScrapeSpaceMarine2Job
    queue: default
    schedule: every monday at 1:56pm

  scrape_spider_man_2_patches:
    class: ScrapeSpiderMan2Job
    queue: default
    schedule: every monday at 1:57pm

  scrape_roblox_patches:
    class: ScrapeRobloxJob
    queue: default
    schedule: every monday at 2pm

  scrape_clash_royale_patches:
    class: ScrapeClashRoyaleJob
    queue: default
    schedule: every monday at 3pm

  scrape_clash_of_clans_patches:
    class: ScrapeClashOfClansJob
    queue: default
    schedule: every monday at 4pm

  scrape_call_of_duty_black_ops_7_updates:
    class: ScrapeCallOfDutyBlackOps7Job
    queue: default
    schedule: every monday at 4:30pm

  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
